require("edward.options")
require("edward.keymaps")
require("edward.plugins")
require("edward.colorscheme")

require("edward.plugins.neotree")
require("edward.plugins.treesitter")
require("edward.plugins.cmp")
require("edward.plugins.comment")
require("edward.plugins.lualine")
require("edward.plugins.telescope")
require("edward.plugins.autopairs")
require("edward.plugins.gitsigns")
require("edward.plugins.bufferline")

require("edward.plugins.lsp.mason")
require("edward.plugins.lsp.lspconfig")
require("edward.plugins.lsp.lspsaga")
require("edward.plugins.lsp.null-ls")
